version: "3.5"
services:
  kong:
    image: kong:3.0.0-alpine
    ports:
      - 18000:8000
      # - 8443:8443
      - 8001:8001
      # - 8444:8444
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql
      KONG_PG_USER: root
      KONG_PG_PASSWORD: root
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      - postgresql

  konga:
    image: pantsel/konga:0.14.9
    ports:
      - 28080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    depends_on:
      - postgresql

  orion:
    image: fiware/orion:3.7.0
    ports:
      - 1026:1026
    command: [ "-dbhost", "mongodb" ]
    environment:
      ORION_MONGO_HOST: mongodb:27018
      ORION_PORT: 1026
      ORION_LOG_LEVEL: INFO
    depends_on:
      - mongodb

  cygnus:
    image: fiware/cygnus-ngsi:2.19.0
    environment:
      CYGNUS_MONGO_HOSTS: mongodb:27018
      CYGNUS_MONGO_SERVICE_PORT: 5050
      CYGNUS_LOG_LEVEL: DEBUG
      CYGNUS_SERVICE_PORT: 5055
      CYGNUS_API_PORT: 5080
    ports:
      - 5080:5080
      - 5050:5050
      - 5055:5055
    depends_on:
      - mongodb

  # sth-comet:
  #   image: fiware/sth-comet:2.9.0
  #   ports:
  #     - 8666:8666
  #   environment:
  #     STH_HOST: 0.0.0.0
  #     STH_PORT: 8666
  #     DB_PREFIX: sth_
  #     DB_URI: mongodb:27017
  #     LOGOPS_LEVEL: DEBUG
  #   depends_on:
  #     - mongodb

  # MongoDB used by Orion, Cygnus and STH-Comet
  mongodb:
    image: mongo:3.6
    ports:
      - 27018:27018
    volumes:
      - ./data/mongodb:/data/db
      - ./data/configdb:/data/configdb

  # PostgreSQL used by Kong
  postgresql:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root
