version: "3.5"
services:
  kong:
    image: kong:3.0.0-alpine
    ports:
      - 8000:8000
      # - 8443:8443
      - 8001:8001
      # - 8444:8444
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: postgresql
      KONG_PG_USER: root
      KONG_PG_PASSWORD: root
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    depends_on:
      - postgresql
    networks:
      - default

  konga:
    image: pantsel/konga:0.14.9
    ports:
      - 8080:8080
    environment:
      HOST: 0.0.0.0
      PORT: 8080
    depends_on:
      - postgresql
    networks:
      - default

  orion:
    image: fiware/orion:3.7.0
    ports:
      - 1026:1026
    environment:
      ORION_MONGO_HOST: mongodb:27017
      ORION_PORT: 1026
      ORION_LOG_LEVEL: INFO
    depends_on:
      - mongodb
    networks:
      - default

  cygnus:
    image: fiware/cygnus-ngsi:2.19.0
    environment:
      CYGNUS_MONGO_HOSTS: mongodb:27017
      CYGNUS_MONGO_SERVICE_PORT: 5050
      CYGNUS_LOG_LEVEL: DEBUG
      CYGNUS_SERVICE_PORT: 5050
      CYGNUS_API_PORT: 5080
    ports:
      - 5080:5080
      - 5050:5050
      - 5055:5055
    depends_on:
      - mongodb
    networks:
      - default

  sth-comet:
    image: fiware/sth-comet:2.9.0
    ports:
      - 8666:8666
    environment:
      STH_HOST: 0.0.0.0
      STH_PORT: 8666
      DB_PREFIX: sth_
      DB_URI: mongodb:27017
      LOGOPS_LEVEL: DEBUG
    depends_on:
      - mongodb
    networks:
      - default
  
  wirecloud:
    image: fiware/wirecloud:1.2
    ports:
      - 28080:8000
    environment:
      DB_HOST: postgresql-wirecloud
      DB_NAME: wirecloud
      DB_USERNAME: root
      DB_PASSWORD: root


  # MongoDB used by Cygnus and STH-Comet
  mongodb:
    image: mongo:5.0
    command: mongod --port 27017
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./data/mongodb:/data/db
      - ./data/configdb:/data/configdb
    networks:
      - default

  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb
    networks:
      - default

  # PostgreSQL used by Kong
  postgresql:
    image: postgres:9.6
    ports:
      - 5432:5432
    volumes:
      - ./data/postgres:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: kong
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root
    networks:
      - default
  
  postgresql-wirecloud:
    image: postgres:9.6
    ports:
      - 15432:5432
    volumes:
      - ./data/postgres-wirecloud:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_DB: wirecloud
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8"
    hostname: postgres
    user: root
    networks:
      - default


  pgadmin:
    image: dpage/pgadmin4:6.12
    ports:
      - 18080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
