name: test build

on:
  push:
    push:
      - main


jobs:
  test_build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout 
        uses: actions/checkout@v3

      - name: setup database
        timeout-minutes: 1
        run: |
          make build

      - name: launch servers
        run: |
          make serve
